algoritmo "semnome"
// Função :
// Autor :
// Data : 30/09/2025
// Seção de Declarações 
var
nome, sexo: caractere
x, h, m: inteiro
inicio
para x de 1 ate 5 faca
limpatela
escreva("Digite o nome: ")
leia(nome)
escreva("H - Homem ou M - Mulher: ")
leia(sexo)
escolha sexo
caso "H"
h <- h + 1
caso "M"
m <- m + 1
outrocaso
escreval("Sexo só pode ser H ou M!")
fimescolha
fimpara
// Seção de Comandos 
fimalgoritmo
