algoritmo "semnome"
// Função :
// Autor :
// Data : 30/09/2025
// Seção de Declarações 
var
x, num, intervalo: inteiro
inicio
para x de 1 ate 80 faca
     escreva("Digite um número: ")
     se num >= 10 entao
        se num <= 150 entao
           intervalo <- intervalo + 1
        fimse
     fimse
fimpara

escreval("Ao total, foram digitados",intervalo,"números no intervalo entre 10 e 150")

// Seção de Comandos 
fimalgoritmo
