algoritmo "Maior ou menor de idade"
// Função :Lê a idade de 75 pessoas e mostra se cada uma é maior ou menor de idade (18 anos).
// Autor :
// Data : 30/09/2025
// Seção de Declarações 
var
x, idade: inteiro

inicio
para x de 1 ate 75 faca
escreva("Digite a idade: ")
leia(idade)
se idade >= 18 entao
escreval("Fulano é maior de idade!")
fimse
fimpara
// Seção de Comandos 
fimalgoritmo

