algoritmo "semnome"
// Função :
// Autor :
// Data : 29/09/2025
// Seção de Declarações 
var
i, N, num, maior: inteiro
inicio
 maior <- 0

   escreva("Digite a quantidade de números (N): ")
   leia(N)

   Para i de 1 ate N faca
      escreva("Digite o ", i, "º número: ")


      Se num > maior entao
         maior <- num
      FimSe
   FimPara

   escreval("O maior número é: ", maior)
// Seção de Comandos 
fimalgoritmo
