algoritmo "semnome"
// Função :
// Autor :
// Data : 29/09/2025
// Seção de Declarações 
var
distancia, combustivel, consumoMedio: real
inicio
escreva("Digite a distância total percorrida (km): ")
leia(distancia)
escreva("Digite o total de combustível gasto (litros): ")
leia(combustivel)
consumoMedio <- distancia / combustivel
escreval("O consumo médio do automóvel é: ", consumoMedio:0:2, " km/l")
// Seção de Comandos 
fimalgoritmo
