algoritmo "semnome"
// Função :
// Autor :
// Data : 29/09/2025
// Seção de Declarações 
var
i, quantidadeAzul: inteiro
nome, cor: caractere
inicio
quantidadeAzul <- 0
Para i de 1 ate 20 faca
escreva("Digite o nome do carro: ")
leia(nome)
escreva("Digite a cor do carro: ")
leia(cor)
Se cor = "azul" entao
quantidadeAzul <- quantidadeAzul + 1
FimSe
FimPara
escreval("Quantidade de carros azuis: ", quantidadeAzul)
// Seção de Comandos 
fimalgoritmo
